function [m_SP__pp,dm_SP__pp] = PA_C8_post_processing(m_SP,dm_SP)
    
    % Post processing
    sums_m_SP = [sum(m_SP(1,1:4),2) sum(m_SP(1,5:6),2)];
    m_SP__pp = [m_SP(:,1:4)/sums_m_SP(1,1)...
        m_SP(:,5:6)/sums_m_SP(1,2)];

    dm_SP__pp = cat(2,(dm_SP(:,1:4,:)*sums_m_SP(1,1) - ...
        bsxfun(@times,m_SP(:,1:4),sum(dm_SP(:,1:4,:),2)))/...
        sums_m_SP(1,1)^2,...
        (dm_SP(:,5:6,:)*sums_m_SP(1,2) - ...
        bsxfun(@times,m_SP(:,5:6),sum(dm_SP(:,5:6,:),2)))/...
        sums_m_SP(1,2)^2);

    % m_SP__pp = m_SP;
    % dm_SP__pp = dm_SP;    
end

